### ISSUE TITLE
NamedNode is not generic

### ISSUE THREAD

**Issue by retog** [tpluscode/rdf-string#13]
I'm getting the following error because type declarations use `NamedNode` with a type parameter.

```
node_modules/@tpluscode/rdf-string/lib/nquads.d.ts:18:132 - error TS2315: Type 'NamedNode' is not generic.

18 export declare const nquads: (strings: TemplateStringsArray, ...values: Value<TemplateResult<NQuadsOptions>, BlankNode | Literal | 
NamedNode<string>>[]) => TemplateResult<NQuadsOptions>;
```

The `.d.ts` files get generated like that despite the fact that the ts code contains no such argument. It seems to be a bug in typescript that is solved by updating typescript.

**Comment by tpluscode** [comment]
This has nothing to do with Typescript. The output `nquads.d.ts` is exactly the same.

The generic type argument was added in DefinitelyTyped/DefinitelyTyped#45260. I would guess that you need to upgrade `@types/rdf-js` on your end to `^3.0.1`

**Comment by retog** [comment]
With typescript 3.9.5 it generates the following in `nquads.d.ts`:

```
export declare const nquads: (strings: TemplateStringsArray, ...values: Value<TemplateResult<NQuadsOptions>, NamedNode | Literal | BlankNode>[]) => TemplateResult<NQuadsOptions>;
```

With typescript 3.8.3 and all else being the same:
```
export declare const nquads: (strings: TemplateStringsArray, ...values: Value<TemplateResult<NQuadsOptions>, BlankNode | Literal | NamedNode<string>>[]) => TemplateResult<NQuadsOptions>;
```
A patch update (3.0.0 -> 3.01) should not break the API and it seems that it doesn't as long as a newer TypeScript version is used. Things would be different if you would use the type parameter in the code, but like that, it seems pointless to add such a type parameter in the `.d.ts.`-file

**Comment by tpluscode** [comment]
Oh, you're right, sorry. I hilariously failed to check the builds properly 🤦 

It is a coincidence though that a newer version typescript does not insert the default type argument values. I would not say it was a bug. After all, `NamedNode` and `NamedNode<string>` are equal in the latest types.

I wonder, what is the output of `npm ls @types/rdf-js` or `yarn why @types/rdf-js` in your repo?

**Comment by tpluscode** [comment]
I merged you PR but I see that this will not (yet) solve the problem. For example `lib/syntax/xsd.d.ts`

```
declare const _default: {
    string: import("rdf-js").NamedNode<string>;
```

Every single package will have to rebuilt to remove the unnecessary generics 😞
