### ISSUE TITLE
namespace is not a function

### ISSUE THREAD

**Issue by retog** [tpluscode/rdf-string#15]
I double checked that my project has no older dependency than the ones in `rdf-string` but I'm still getting the following error:

```
    C:\Users\me\Documents\retog\rdfjs-dataset-sparql\node_modules\@tpluscode\rdf-ns-builders\vocabularies\as.js:1
    TypeError: namespace is not a function

      at Object.<anonymous> (node_modules/@tpluscode/rdf-ns-builders/vocabularies/as.js:2:19)
          at Object.<anonymous> (C:\Users\me\Documents\retog\rdfjs-dataset-sparql\node_modules\@tpluscode\rdf-ns-builders\index.js:1)
```

Any idea what could be causing this?

**Comment by tpluscode** [comment]
Is your project written for node and `type: module`?

**Comment by retog** [comment]
I use node to run the tets with jest, but I don't specify `type: module`. My code is here: https://github.com/retog/rdfjs-dataset-sparql

**Comment by tpluscode** [comment]
Good lord, I am so tired of the commonjs/esm nonsense

In more recent versions jest starts to support native es modules. It seems to break transitive packages which export with [esm](https://npm.im/esm). Unfortunately I am yet to find a better solution for dual-targeting packages.

**Comment by tpluscode** [comment]
Try with rdf-string `0.2.16`

**Comment by tpluscode** [comment]
I believe it's fixed. Please reopen if necessary
